#+TITLE: Proton's Emacs Configuration
** Dependencies for installation
In order for LSP functionality to work, you want to install the [[https://github.com/emacs-lsp/lsp-mode#supported-languages][LSP servers]] listed on the =lsp-mode= repository.
This config also requires emacs27+ to work correctly.
** Configuration of built-in features
*** Autosave and backup file settings
This disables Emacs's default autosave and backup files.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+END_SRC
*** Remove the startup screen
This removes the useless startup screen in Emacs. It'll be replaced with [[https://github.com/emacs-dashboard/emacs-dashboard][emacs-dashboard]].
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen t)
#+END_SRC
*** Interpret a new alias for yes/no
This simple line allows for yes/no to be answered with y/n. Saves a bit of time.
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
*** Set default shell in the terminal
Set your own default shell here for M-x term. It's a nice terminal for most uses.
#+BEGIN_SRC emacs-lisp
  (defvar default-shell "/bin/zsh")
  (defadvice term (before force-bash)
    (interactive (list default-shell)))
  (ad-activate 'term)
#+END_SRC
*** Line-by-line scrolling
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC
*** Removing bars
I remove the toolbar and menubar so as to have less useless elements clutter the screen.
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
#+END_SRC
*** Programming mode-related tweaks
By default, Emacs doesn't enable line numbers with =(global-display-line-numbers-mode)=. 
Neither would I, as it isn't really useful for modes outside of programming modes. 
So, I just enable it for programming modes, and leave it off for others.
I also enable =hl-line-mode= for highlighting the current line for visiblity.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'prog-mode-hook 'hl-line-mode)
#+END_SRC
*** Replace functionality fix
By default, Emacs doesn't replace text that you've selected with newly typed text. With this line, text that is selected is deleted, then the new text being typed appears in its place.
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode +1)
#+END_SRC
*** Font setting
This sets up =iosevka= as the font of choice. You can replace it with whatever font you want.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist
	       '(font . "Iosevka-10"))
#+END_SRC
*** Change undo binding
For this, I unset the default binding for =C-z= (which is to suspend an emacs frame) and set it to be 
undo like most other programs.
#+BEGIN_SRC emacs-lisp
  (global-unset-key "\C-z")
  (global-set-key "\C-z" 'undo)
#+END_SRC
*** =M-x shell= prompt fix
This fixes the prompt being removable from =M-x shell= by backspacing.
#+BEGIN_SRC emacs-lisp
  (setq comint-prompt-read-only t)
#+END_SRC
** Packages
In this configuration, I use =use-package= to automatically install the packages, 
as well as to setup their configurations.
*** Visuals
**** Org bullets
This sets up some nice bullets for org-mode that look better than the default asterisks used in Emacs.
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
      :hook 
      (org-mode . org-bullets-mode))
#+END_SRC
**** Gruvbox
This installs the [[https://github.com/Greduan/emacs-theme-gruvbox][gruvbox-theme]], which is a really nice dark theme for Emacs and other editors/terminals.
#+BEGIN_SRC emacs-lisp
  (use-package gruvbox-theme
    :config
    (load-theme 'gruvbox-dark-medium t))
#+END_SRC
**** Dashboard
This installs [[https://github.com/emacs-dashboard/emacs-dashboard][emacs-dashboard]], which is a far more customizable and better startup screen than the default.
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :custom
    (dashboard-set-footer nil)
    (dashboard-startup-banner 'logo)
    :config
    (dashboard-setup-startup-hook))
#+END_SRC
*** Programming-related functionality
**** =lsp= completion
This installs [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]], which adds IDE-like functionality to Emacs for certain languages through language servers. It also installs [[https://github.com/emacs-lsp/lsp-ui][lsp-ui]], which adds some extra UI functionality that interfaces with =lsp-mode=.
Completion is provided by [[http://company-mode.github.io/][company]], and the [[https://github.com/tigersoldier/company-lsp][company-lsp]] plugin for company to interface with LSP.
#+BEGIN_SRC emacs-lisp
  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :init
    (setq lsp-keymap-prefix "s-l")
    :hook
    (prog-mode . lsp-deferred))

  (use-package lsp-ui
    :hook
    (lsp-mode . lsp-ui-mode)
    :custom-face
    (lsp-ui-doc-background ((nil (:background "#1d2021")))))

  (use-package lsp-java
    :after lsp
    :hook
    (java-mode . lsp))

  (use-package company
    :hook
    (prog-mode . company-mode)
    :config
    ;; recommended settings by lsp-mode
    (setq company-minimum-prefix-length 1
	  company-idle-delay 0.0))

  (use-package company-lsp
    :defer t
    :commands company-lsp)
#+END_SRC
**** Magit
This installs a package called [[https://github.com/magit/magit][magit]], which allows you to use git within emacs itself. It also configures 
the bindings for =magit-status=, so one can actually use magit with its own seperate buffer in emacs.
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind ("C-x g" . magit-status))
#+END_SRC
*** Media/other desktop functionality
**** EMMS
#+BEGIN_SRC emacs-lisp
  (use-package emms
    :straight (emms :type git :repo "https://git.savannah.gnu.org/git/emms.git")
    :config
    (require 'emms-setup)
    (require 'emms-player-mpd)
    (emms-all)
    :custom
    (emms-seek-seconds 5)
    (emms-player-list '(emms-player-mpd))
    (emms-info-functions '(emms-info-mpd))
    (emms-player-mpd-server-name "localhost")
    (emms-player-mpd-server-port "6600")
    (emms-source-file-default-directory "~/Music/"))
#+END_SRC
